pipeline:

    build-project:
        image: quay.io/ukhomeofficedigital/openjdk8:v1.1.0
        commands:
            - ./gradlew build
            - git rev-parse --abbrev-ref HEAD | xargs echo -n > ./branchName
        when:
            event: [push, pull_request, tag]

    update-semver:
        image: quay.io/ukhomeofficedigital/docker-openjdk8-git:v1.5.0
        secrets:
            - github_ssh_key
        commands:
            - sh /root/git-utilities/set-up-github-user.sh "$${GITHUB_SSH_KEY}"
            - ./gradlew release -Prelease.useAutomaticVersion=true -x runBuildTasks -s -i
            - git describe --abbrev=0 --tags > ./tagSemver
        when:
            branch: [master]
            event: [push]

    docker-build:
        image: docker:17.09.1
        environment:
            - DOCKER_HOST=tcp://172.17.0.1:2375
        commands:
            - docker build -t pttg-ip-api .
        when:
            event: [push, tag]

    install-docker-image-with-githash-tag:
        image: docker:17.09.1
        environment:
            - DOCKER_HOST=tcp://172.17.0.1:2375
        secrets:
            - docker_password
        commands:
            - docker login -u="ukhomeofficedigital+pttg" -p=$${DOCKER_PASSWORD} quay.io
            - docker tag pttg-ip-api quay.io/ukhomeofficedigital/pttg-ip-api:${DRONE_COMMIT_SHA:0:8}
            - docker push quay.io/ukhomeofficedigital/pttg-ip-api:${DRONE_COMMIT_SHA:0:8}
        when:
            event: push

    install-docker-image-from-feature-branch-build:
        image: docker:17.09.1
        environment:
            - DOCKER_HOST=tcp://172.17.0.1:2375
        secrets:
            - docker_password
        commands:
            - docker login -u="ukhomeofficedigital+pttg" -p=$${DOCKER_PASSWORD} quay.io
            - docker tag pttg-ip-api quay.io/ukhomeofficedigital/pttg-ip-api:$(cat ./branchName)
            - docker push quay.io/ukhomeofficedigital/pttg-ip-api:$(cat ./branchName)
        when:
            branch: EE*
            event: push

    install-docker-image-from-master-branch-build:
        image: docker:17.09.1
        environment:
            - DOCKER_HOST=tcp://172.17.0.1:2375
        secrets:
            - docker_password
        commands:
            - docker login -u="ukhomeofficedigital+pttg" -p=$${DOCKER_PASSWORD} quay.io
            - docker tag pttg-ip-api quay.io/ukhomeofficedigital/pttg-ip-api:latest
            - docker push quay.io/ukhomeofficedigital/pttg-ip-api:latest
            - docker tag pttg-ip-api quay.io/ukhomeofficedigital/pttg-ip-api:build-$${DRONE_BUILD_NUMBER}
            - docker push quay.io/ukhomeofficedigital/pttg-ip-api:build-$${DRONE_BUILD_NUMBER}
            - docker tag pttg-ip-api quay.io/ukhomeofficedigital/pttg-ip-api:$(cat ./tagSemver)
            - docker push quay.io/ukhomeofficedigital/pttg-ip-api:$(cat ./tagSemver)
        when:
            branch: [master]
            event: push

    tag-docker-image-with-git-tag:
        image: docker:17.09.1
        environment:
            - DOCKER_HOST=tcp://172.17.0.1:2375
        secrets:
            - docker_password
        commands:
            - docker login -u="ukhomeofficedigital+pttg" -p=$${DOCKER_PASSWORD} quay.io
            - docker tag pttg-ip-api quay.io/ukhomeofficedigital/pttg-ip-api:$${DRONE_TAG}
            - docker push quay.io/ukhomeofficedigital/pttg-ip-api:$${DRONE_TAG}
            - docker tag pttg-ip-api quay.io/ukhomeofficedigital/pttg-ip-api:${DRONE_COMMIT_SHA:0:8}
            - docker push quay.io/ukhomeofficedigital/pttg-ip-api:${DRONE_COMMIT_SHA:0:8}
            - docker tag pttg-ip-api quay.io/ukhomeofficedigital/pttg-ip-api:$(cat ./tagSemver)
            - docker push quay.io/ukhomeofficedigital/pttg-ip-api:$(cat ./tagSemver)
        when:
            event: tag

    clone-kube-project:
        image: plugins/git
        commands:
            - git clone https://github.com/UKHomeOffice/kube-pttg-ip-api.git
        when:
            event: [push, tag, deployment]

    deploy-to-dev-from-build-number:
        image: quay.io/ukhomeofficedigital/kd:v1.14.0
        environment:
            - KUBE_NAMESPACE=pttg-ip-dev
            - ENVIRONMENT=dev
            - VERSION=build-${DRONE_BUILD_NUMBER}
            - KUBE_SERVER=https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
        secrets:
            - pttg_ip_dev
        commands:
            - cd kube-pttg-ip-api
            - ./deploy.sh
        when:
            branch: [master]
            event: [push, tag]

    deployment:
        image: quay.io/ukhomeofficedigital/kd:v1.14.0
        environment:
            - KUBE_NAMESPACE=pttg-ip-${DRONE_DEPLOY_TO}
            - ENVIRONMENT=${DRONE_DEPLOY_TO}
            - KUBE_SERVER=https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
        secrets:
            - pttg_ip_dev
            - pttg_ip_test
        commands:
            - cd kube-pttg-ip-api
            - ./deploy.sh
        when:
            event: deployment
            environment: [dev, test, preprod]

    deploy-to-prod:
        image: quay.io/ukhomeofficedigital/kd:v1.14.0
        environment:
            - KUBE_NAMESPACE=pttg-ip-pr
            - ENVIRONMENT=pr
            - VERSION=${IMAGE_VERSION}
            - KUBE_SERVER=https://kube-api-prod.prod.acp.homeoffice.gov.uk
        secrets:
            - pttg_ip_pr
        commands:
            - cd kube-pttg-ip-api
            - ./deploy.sh
        when:
            event: deployment
            environment: pr
