pipeline:

  docker-build-db-image:
    privileged: true
    image: docker:1.11
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - docker build -t pttg-postgres -f Dockerfile-pttg-postgres .
    when:
      branch: [master, refs/tags/*]
      event: [push, tag]

  tag-db-image:
    image: docker:1.11
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+pttg" -p=${DOCKER_PASSWORD} quay.io
      - docker tag pttg-postgres quay.io/ukhomeofficedigital/pttg-postgres:latest
      - docker push quay.io/ukhomeofficedigital/pttg-postgres:latest
    when:
      branch: master
      event: push

services:
  dind:
    image: docker:1.11-dind
    privileged: true
    command:
      - "-s"
      - "overlay"
